server:
  port: 8181


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_security_role
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

## DB is not used in this application, it could be removed
secret:
  key: testsecret